# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title myFunction
#' @description
#' Modify a string in Rcpp.
#' @name myFunction
#' @param x a vector of strings
#' @examples
#' myFunction(x=c('Hello', "C++", 'header', 'files'))
#' 
#' @export
myFunction <- function(x) {
    .Call('myRpackage_myFunction', PACKAGE = 'myRpackage', x)
}

